[bar/example]
monitor = ${env:MONITOR:}
width = 100%
height = 30
background = #2c2c54
foreground = #ffffff
border-size = 2
border-color = #6a0dad
;padding-left = 10
padding-right = 4
modules-left = i3
modules-center = memory
modules-right = cpu player wifi bluetooth clock backlight battery
font-0 = Noto Sans:size=10;2
# font-1 = Font Awesome 6 Free Solid:size=10;2
font-1 = "Symbols Nerd Font:size=12;2"
font-2 = Font Awesome 6 Brands:size=10;2
font-3 = DejaVu Sans Mono:size=10;2
font-4 = Nerd Font:style=Regular:size=12;0
font-5 = NotoEmoji:scale=10;
font-6 = ttf-arimo-nerd:scale=10

separator = |
separator-foreground = #6a0dad
separator-padding = 3


[internal/tray]
screenchange-reload = false
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
format-spacing = 5
format-padding = 5
format-margin = 5
format-offset = 5
pseudo-transparency = false



; Enables pseudo-transparency for the bar
; If set to true the bar can be transparent without a compositor.

[module/i3]
type = internal/i3
index-sort = true
sort-workspaces = true
pin-workspaces = true
ws-icon-0 = 1;♚
ws-icon-1 = 2;♛
ws-icon-2 = 3;♜
ws-icon-3 = 4;♝
ws-icon-4 = 5;♞
ws-icon-default = ♟
format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 3
label-mode-background = #6a0dad
label-focused = %index%
label-focused-foreground = #ffffff
label-focused-background = #4b0082
label-focused-underline = #9370db
label-focused-padding = 3
label-unfocused = %index%
label-unfocused-foreground = #dcdcdc
label-unfocused-background = #2c2c54
label-unfocused-underline = #483d8b
label-unfocused-padding = 3
label-visible = %index%
label-visible-foreground = #d8bfd8
label-visible-background = #3b3b6d
label-visible-underline = #9370db
label-visible-padding = 3
label-urgent = %index%
label-urgent-foreground = #ffffff
label-urgent-background = #8b0000
label-urgent-underline = #ff4500
label-urgent-padding = 3


; Separator in between workspaces
;label-separator = |
;label-separator-padding = 2
;label-separator-foreground = #ffb52a

[module/memory]
type = internal/memory
interval = 2
;format = "%{T3}%{T-} Memory: %used% / %total% MB (%percentage_used%%)"
format = "<label> <bar-used>"
format-foreground = #ffffff
format-background = #4b0082
format-padding = 5
label = RAM %gb_used%/%gb_free%
bar-used-indicator =
bar-used-width = 50
bar-used-foreground-0 = #55aa55
bar-used-foreground-1 = #557755
bar-used-foreground-2 = #f5a70a
bar-used-foreground-3 = #ff5555
bar-used-fill = ▐
bar-used-empty = ▐
bar-used-empty-foreground = #444444



[module/cpu]
type = internal/cpu
interval = 1
format = <label> <ramp-coreload>
label = CPU %percentage%%
format-foreground = #ffffff
format-background = #6a0dad
format-padding = 5
ramp-coreload-spacing = 1
ramp-coreload-0 = ▁
ramp-coreload-1 = ▂
ramp-coreload-2 = ▃
ramp-coreload-3 = ▄
ramp-coreload-4 = ▅
ramp-coreload-5 = ▆
ramp-coreload-6 = ▇
ramp-coreload-7 = █
ramp-coreload-foreground = #ffffff

label-warn = CPU %percentage%%


[module/wifi]
type = internal/network
interface = wlan0
interface-type = wireless
interval = 3.0
udspeed-minwidth = 5
accumulate-stats = true
unknown-as-up = true
speed-unit = ''
format-connected = %{A1:alacritty -e nmtui:} <label-connected> <ramp-signal> %{A}
format-disconnected = <label-disconnected>
format-packetloss = <animation-packetloss> <label-connected>
label-connected = %essid% at
label-connected-foreground = #eefafa
label-disconnected = not connected
label-disconnected-foreground = #66ffff
ramp-signal-0 = 0%
ramp-signal-1 = 20%
ramp-signal-2 = 40%
ramp-signal-3 = 60%
ramp-signal-4 = 80%
ramp-signal-5 = 100%
animation-packetloss-0 = ⚠
animation-packetloss-0-foreground = #ffa64c
animation-packetloss-1 = 📶
animation-packetloss-1-foreground = #000000
animation-packetloss-framerate = 500

[module/bluetooth]
type = custom/script
exec = /home/ion606/.config/polybar/scripts/bluetooth_status.sh
interval = 1
click-left = blueman-manager &


[module/player]
type = internal/pulseaudio
use-ui-max = true
interval = 5
label-background = #aaaaaa
label-volume-low-foreground = #aaaaaa
label-volume-medium-foreground = #ffaa00
label-volume-high-foreground = #33cc33
label-volume-muted-foreground = #ff3333
reverse-scroll = false
format-volume = audio <ramp-volume> <label-volume>
label-muted = "%{T0}🔇 muted%{T-}"
label-muted-foreground = #ff0000
ramp-volume-0 = "%{T0}🔈%{T-}"
ramp-volume-1 = 🔉
ramp-volume-2 = 🔊
click-right = pavucontrol


[module/clock]
type = internal/date
interval = 1.0
date = %Y-%m-%d
time = %H:%M:%S
date-alt = %m/%d/%Y
time-alt = %m/%d/%Y
format = %{T1} 🕓 <label> %{T-}
format-background = #2c2c54
format-foreground = #ffffff
label = %{T1} %time% %{T-}
time-padding = 5
click-left = toggle

[module/windows]
type = custom/script
exec = ~/.config/polybar/scripts/windows.sh
interval = 1
label = %output%
click-left = xdotool windowactivate $(xdotool getwindowfocus)


[module/backlight]
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
; Default: first usable card in /sys/class/backlight (new in version 3.7.0)
card = intel_backlight
use-actual-brightness = true
poll-interval = 0
enable-scroll = true

; Interval for changing the brightness (in percentage points).
; New in version 3.7.0
; Default: 5
scroll-interval = 10

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp>

; Available tokens:
;   %percentage% (default)
label = %percentage%%

; Only applies if <ramp> is used
# 🌒 🌓 🌖 🌕 🌔 🌗 🌘
ramp-0 = 🌑
ramp-1 = 🌒
ramp-2 = 🌓
ramp-3 = 🌔
ramp-4 = 🌕


[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
; Default: 100
full-at = 98

; format-low once this charge percentage is reached
; Default: 10
; New in version 3.6.0
low-at = 20

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT1
adapter = ADP1

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = ⚡ <animation-charging>  <label-charging>

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
; format-discharging = <ramp-capacity>  <label-discharging>

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
format-full = <ramp-capacity>  <label-full>

; Format used when battery level drops to low-at
; If not defined, format-discharging is used instead.
; Available tags:
;   <label-low>
;   <animation-low>
;   <bar-capacity>
;   <ramp-capacity>
; New in version 3.6.0
format-low = <label-low>  <animation-low>

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
label-full = %percentage%% ^~^

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
; New in version 3.6.0
label-low = BATTERY LOW AT %percentage%

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-low> is used
; New in version 3.6.0
animation-low-0 = ⚠️
animation-low-1 = ⚠️
animation-low-2 = ⚠️
animation-low-3 = 
animation-low-4 = 
animation-low-5 = 
animation-low-framerate = 600
